const TRACK_TYPES = {
  VIDEO: 1,
  AUDIO: 2,
  COMPLEX: 3,
  LOGO: 16,
  SUBTITLE: 17,
  BUTTONS: 18,
  CONTROL: 32
}

const CODEC_IDS = {
  V_MPEG4_ISO_AVC: 'V_MPEG4/ISO/AVC',
  V_MPEGH_HEVC: 'V_MPEGH/ISO/HEVC',
  A_AAC: 'A_AAC',
  A_AC3: 'A_AC3',
  A_EAC3: 'A_EAC3',
  A_MPEG_L3: 'A_MPEG/L3',
  A_OPUS: 'A_OPUS',
  A_VORBIS: 'A_VORBIS',
  S_TEXT_UTF8: 'S_TEXT/UTF8',
  S_TEXT_ASS: 'S_TEXT/ASS',
  S_TEXT_SSA: 'S_TEXT/SSA',
  S_TEXT_USF: 'S_TEXT/USF',
  S_TEXT_WEBVTT: 'S_TEXT/WEBVTT'
}

module.exports = { TRACK_TYPES, CODEC_IDS }
